apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasm-http-deployment
  labels:
    app: wasm-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wasm-http
  template:
    metadata:
      labels:
        app: wasm-http
    spec:
      runtimeClassName: wasmedge
      containers:
        - name: wasm-http-server
          image: 577438315497.dkr.ecr.ap-northeast-1.amazonaws.com/we:latest
          ports:
            - containerPort: 1234
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: wasm-http-service
  labels:
    app: wasm-http
spec:
  selector:
    app: wasm-http
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1234
  type: LoadBalancer
